{% set name = "Orange3-ImageAnalytics" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd579a73fef8e797b71288f639d066786dd545cd87e11e5ed7f229e732c0a7e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python          >=3.6
    - setuptools
    - pip
  run:
    - python          >=3.6
    - scipy
    - hypertemp
    - numpy           >=1.10.0
    - orange3         >=3.3.5
    - pillow          >=4.2.1
    - requests
    - cachecontrol
    - lockfile
    - lap             >=0.3.0
    - ndf             >=0.1.4

test:
  imports:
    - orangecontrib.imageanalytics

about:
  home: https://github.com/biolab/orange3-imageanalytics
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Orange3 add-on for dealing with image related tasks'

  description: |
    Orange3 Image Analytics is an add-on for the Orange3 data mining suite.
    It provides extensions for importing/creating labeled image data sets and
    embedding them through a variety of pre-trained deep neural networks.
  doc_url: http://orange3-imageanalytics.readthedocs.io
  dev_url: https://github.com/biolab/orange3-imageanalytics

extra:
  recipe-maintainers:
    - primozgodec
    - astaric
