appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ltkr/tjF7Tw8BFVC6SObk8AB6AbkLhtKlx9JZT592aq07cdmISm0IqHG4CLTnAeJCrglgq9NIvFrA9fSD4pka/kiOC6UHwXFJHTUeeJO0J8C3xXfQnlf1HTUyjwE+zoJGgcgUDpXNkEfiK+wQ7Ex5ytTpU2oZ/D9zNgOwSh7KgLWLper/fLGChAkwgYy60bXg1WNyXIXaF9XcN4K1TuOSDeTnuTeh/1OLUZSNRHq90whwyvDIOW3XmITUPPT7NbYD/HF7l6obCq9bqfFe3LIomNoUflVF8LB0T/+nWA70j2MEnZ5HijipmIHCAmC7uXCoxDFk2vwG/wTGGtBgHaTHcQF/e7msHmsUJ0c8YogpFYg2xFEaK5NtBuUfRiURV+lrafDM2HLNCFy1rdVULYoXhcjmmkjeOBfCpPL/x3xP9VQberfiBAWSNI493Qus3QG5BoB4Um7UPjxsS97ig7+h3wVAsKjxJi+BgiwX9as5uM7gkQjeCZMcDtUqc1uVZCtl76IRj39wCykB1Mr1cDaBMuRvywvCdRk91LPdNlr7fofsh2MdIJcrJ1FOj0YWC2ZoUsCC7xjf8nS+bl3wuVG7amnb5JA1GX3AAUqY6sv8AluyYI0IEMu1/aMRsKzQ6QgbRRTOhvHZNpnrN2+1P8OSuobSH+1ZKF33ayP4ruGRJ4=}
provider:
  win: azure
conda_forge_output_validation: true
